image: node:latest

stages:
  - test
  - stagingFrontend

frontend_tests:
  stage: stagingFrontend
  before_script:
    - cd Frontend/reveal.me
    - npm install --legacy-peer-deps
  # image: ruby:latest
  script:
    # - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    - npm run cypress:headless

backend_tests:
  before_script:
    - cd Backend/reveal.me && npm install
  stage: test
  script:
    - npm test
 