image: node:16.5.0

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cd Frontend/reveal.me
    - npm install -save --legacy-peer-deps
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH