variables:
  IMAGE_NAME: revealme/reveal.me2022
  IMAGE_TAG: node_project

stages:
  - test
  - build

backend_tests:
  stage: test
  image: node:18.6-buster-slim
  before_script:
    - cd Backend/reveal.me && npm install
  script:
    - npm test

build_image:
  stage: build
  image: docker:20.10.16
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script: 
    - echo $DOCKER_USER
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
