image: node:latest

stages:
  - test
  - staging
  # - stagingFrontend

hosting_backend:
  stage: staging
  before_script:
    - cd Backend/reveal.me
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - npm install
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    # - npm start

# start_Frontend:
#   stage: stagingFrontend
#   before_script:
#     - cd Frontend/reveal.me
#     - npm install --legacy-peer-deps
#   # image: ruby:latest
#   script:
#     # - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#     - npm run dev

# backend_tests:
#   before_script:
#     - cd Backend/reveal.me && npm install
#   stage: test
#   script:
#     - npm test
 