stages:
  - test
  - staging
  - production

staging:
  type: deploy
  stage: staging
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - staging

production:
  type: deploy
  stage: production
  image: ruby:latest
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master


backend_tests:
  image: node:18.6-buster-slim
  stage: test
  before_script:
    - cd Backend/reveal.me && npm install
  script:
    - npm test
 